"""ALiver Windows Bridge package initialization."""

from bridge.audio_device_family_patch import install_audio_device_family_patch
from bridge.audio_environment_patch import install_audio_environment_patch
from bridge.audio_scan_guard_patch import install_audio_scan_guard_patch
from bridge.avatar_action_control import install_avatar_action_control_patch
from bridge.avatar_action_duration_fix import install_avatar_action_duration_fix
from bridge.control_guard_install_patch import install_control_guard_install_patch
from bridge.fast_startup_patch import install_bridge_fast_startup_patch
from bridge.live_debug_defaults import install_live_debug_defaults
from bridge.live_debug_json_safety_patch import install_live_debug_json_safety_patch
from bridge.realtime_voice_dsp_granular_patch import (
    install_realtime_voice_dsp_granular_patch,
)
from bridge.realtime_voice_dsp_output_guard_patch import (
    install_realtime_voice_dsp_output_guard_patch,
)
from bridge.realtime_voice_dsp_route_guard import install_realtime_voice_dsp_route_guard
from bridge.realtime_voice_dsp_stable_engine_patch import (
    install_realtime_voice_dsp_stable_engine_patch,
)
from bridge.startup_retry_patch import install_bridge_startup_retry_patch
from bridge.vtube_motion import install_vtube_motion_patch
from bridge.vtube_motion_control import install_vtube_motion_control_patch
from bridge.vtube_motion_safety import install_vtube_motion_safety_patch
from bridge.vtube_motion_v2 import install_vtube_motion_v2_patch
from bridge.vtube_studio_auth_fix import install_vtube_studio_auth_fix

install_bridge_fast_startup_patch()
install_audio_device_family_patch()
install_audio_scan_guard_patch()
install_realtime_voice_dsp_route_guard()
install_realtime_voice_dsp_stable_engine_patch()
install_realtime_voice_dsp_output_guard_patch()
install_realtime_voice_dsp_granular_patch()
install_audio_environment_patch()
install_live_debug_defaults()
install_vtube_studio_auth_fix()
install_vtube_motion_patch()
install_vtube_motion_safety_patch()
install_vtube_motion_v2_patch()
install_avatar_action_control_patch()
install_avatar_action_duration_fix()
install_vtube_motion_control_patch()
install_live_debug_json_safety_patch()
install_bridge_startup_retry_patch()
install_control_guard_install_patch()
